name: Output issues
on: issues
jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
      - name: Get Issue information
        run: |
          echo "Title: ${{ github.event.issue.title }}"
          echo "Body: ${{ github.event.issue.body }}"
